"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://bahai.works/
  name = bahaiworks

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'bahaiworks'
    langs = {
        'en': 'bahai.works',
        'de': 'de.bahai.works',
    }

    def scriptpath(self, code):
        return {
            'en': '',
            'de': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
            'de': 'https',
        }[code]
